on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
name: build
jobs:
  deploy:
    name: deploy-ec2
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: check user
        run: whoami

      - name: stop docker
        run: docker-compose -f docker-compose.dev.yml down

      - name: build docker
        run: docker-compose -f docker-compose.dev.yml build

      - name: run docker
        run: docker-compose -f docker-compose.dev.yml up -d

      # - name: Copy repository contents via scp
      #   uses: appleboy/scp-action@master
      #   env:
      #     HOST: ${{ secrets.HOST }}
      #     USERNAME: ${{ secrets.USERNAME }}
      #     PORT: 22
      #     KEY: ${{ secrets.KEY }}
      #   with:
      #     source: "."
      #     target: "/home/ubuntu/codes/"

      # - name: deploy to EC2
      #   uses: appleboy/ssh-action@master
      #   with:
      #     HOST: ${{ secrets.HOST }}
      #     USERNAME: ${{ secrets.USERNAME }}
      #     PORT: 22
      #     KEY: "${{ secrets.KEY }}"
      #     script: |
      #       git checkout develop
      #       git pull origin develop
      #       git status
      #       docker-compose -f docker-compose.dev.yml build
      #       docker-compose -f docker-compose.dev.yml up -d
