on: push
name: build
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker-compose -f docker-compose.dev.yml build
        run: echo Hello, world!

      # - name: docker-compose -f docker-compose.dev.yml up -d
