on: push
name: build
jobs:
  build:
    name: build
    runs-on: ubuntu-lastest
    steps:
      - uses: actions/checkout@develop
      - name: docker-compose -f docker-compose.dev.yml build
        with:
          args: build
      - name: docker-compose -f docker-compose.dev.yml up -d