on: push
name: build
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker compose build dev
        run: docker-compose -f docker-compose.dev.yml build

      - name: echo env
        run: echo ${{ secrets.USERNAME }}
  deploy:
    name: deploy-ec2
    runs-on: ubuntu-latest
    steps:
      - name: Prepare SSH to work with the remote server
        run: |
          eval $(ssh-agent -s)
          cat "${{ secrets.KEY }}"
          ssh-add -
          chmod 700 ~/.ssh && chmod 600 ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa.pub
          echo "SECRET_KEY ${{ secrets.KEY }}"
          ssh -o StrictHostKeyChecking=no -T "${{ secrets.USERNAME }}@${{ secrets.HOST }}"
      - name: deploy to EC2
        uses: easingthemes/ssh-deploy@main
        env:
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          SSH_PRIVATE_KEY: ${{ secrets.KEY }}
          # port: 22
          script: |
            whoami
          # script: |
          #   cd codes/
          #   git checkout develop
          #   git pull origin develop
          #   git status
          #   docker-compose -f docker-compose.dev.yml build
          #   docker-compose -f docker-compose.dev.yml up -d
