on: push
name: build
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker compose build dev
        run: docker-compose -f docker-compose.dev.yml build

      - name: echo env
        run: echo ${{ secrets.USERNAME }}
  deploy:
    name: deploy-ec2
    runs-on: ubuntu-latest
    steps:
      - name: deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SECRET_KEY }}
          port: 22
          script: |
            cd codes/
            git checkout develop
            git pull origin develop
            git status
            docker-compose -f docker-compose.dev.yml build
            docker-compose -f docker-compose.dev.yml up -d
